#!/bin/bash

CWD="$(pwd)"
DRY_INSTALL_DIR="${CWD}/dry/install"
WET_INSTALL_DIR="${CWD}/wet/install"

if [ -d ./.venv ]; then
    source ./.venv/bin/activate
fi

if [ -f $DRY_INSTALL_DIR/setup.sh ]; then
    source $DRY_INSTALL_DIR/setup.sh
    for f in ./dry/install/*; do
	if [ -d "$f" ]; then
	    PACKAGE_DIR="$( basename "$f" )"
	    package="$DRY_INSTALL_DIR/$PACKAGE_DIR"
	    eval 'export PYTHONPATH=$package:$PYTHONPATH'
	    eval 'export PATH=$package:$PATH'
	fi
    done
fi

if [ -f $WET_INSTALL_DIR/setup.sh ]; then
   source $WET_INSTALL_DIR/setup.sh
   for f in ./wet/install/*; do
       if [ -d "$f" ]; then
	   PACKAGE_DIR="$( basename "$f" )"
	   package="$WET_INSTALL_DIR/$PACKAGE_DIR"
	   eval 'export PYTHONPATH=$package:$PYTHONPATH'
	   eval 'export PATH=$package:$PATH'
       fi
   done
fi

eval 'export PYTHONWARNINGS="ignore"'

export LD_PRELOAD="${CWD}/dry/install/open3d_colcon/lib/libOpen3D.so"
